version: '3.8'
services:
  postgres:
    build:
      context: ./
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=news_test_db
      - POSTGRES_PASSWORD=12345
    volumes:
      - "db-data:/var/lib/postgresql/data"


  news-api:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/news_test_db
      - JS_URL=http://localhost
    image: 'news-api'
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  db-data:




