spring:
  application:
    name: news-api
  profiles:
    active: test
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

---
spring:
  config:
    activate:
      on-profile: prod
    import: optional:configserver:http://localhost:8888
---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/news_test_db
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  cloud:
    config:
      enabled: false

logging:
  level:
    org.springframework.web: ERROR
    ru.clevertec.newsapi: INFO
  file:
    path: logs
