spring:
  application:
    name: news-api
  profiles:
    active: test

server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/news_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/news_test_db
    username: admin
    password: 12345

    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always


