spring:
  application:
    name: news-api
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/news_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

